// <auto-generated />
namespace ZOE.OS.Modelo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Version102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version102));
        
        string IMigrationMetadata.Id
        {
            get { return "201304102104128_Version1.0.2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
