// <auto-generated />
namespace ZOE.OS.Modelo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Version104_ReasignarAsesor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version104_ReasignarAsesor));
        
        string IMigrationMetadata.Id
        {
            get { return "201308012348202_Version1.0.4_ReasignarAsesor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
