// <auto-generated />
namespace ZOE.OS.Modelo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Version101 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version101));
        
        string IMigrationMetadata.Id
        {
            get { return "201304092232216_Version1.0.1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
