// <auto-generated />
namespace ZOE.OS.Modelo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Version103_EnvioCorreo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Version103_EnvioCorreo));
        
        string IMigrationMetadata.Id
        {
            get { return "201304161849510_Version1.0.3_EnvioCorreo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
