// <auto-generated />
namespace ZOE.OS.Modelo.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Eventos_EmailReq_EsCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eventos_EmailReq_EsCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201401240906264_Eventos_EmailReq_EsCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
