//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOE.OrdenesServicio.Views.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZOE.OrdenesServicio.Views.Account.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully!..
        /// </summary>
        public static string CPCambioPassExitoso {
            get {
                return ResourceManager.GetString("CPCambioPassExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CPCampoConfirmarNuevo {
            get {
                return ResourceManager.GetString("CPCampoConfirmarNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string CPCampoConfirmValidacion {
            get {
                return ResourceManager.GetString("CPCampoConfirmValidacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CPCampoPassAct {
            get {
                return ResourceManager.GetString("CPCampoPassAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Current Password field is required..
        /// </summary>
        public static string CPCampoPassActReq {
            get {
                return ResourceManager.GetString("CPCampoPassActReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string CPCampoPassNuevo {
            get {
                return ResourceManager.GetString("CPCampoPassNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The New Password field is required..
        /// </summary>
        public static string CPCampoPassNuevoReq {
            get {
                return ResourceManager.GetString("CPCampoPassNuevoReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} should be at least of {2} characters.
        /// </summary>
        public static string CPCampoPassNuevoValLen {
            get {
                return ResourceManager.GetString("CPCampoPassNuevoValLen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password must be at least {0} characters long.
        /// </summary>
        public static string CPPaginaSubtitulo {
            get {
                return ResourceManager.GetString("CPPaginaSubtitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string CPPaginaTitulo {
            get {
                return ResourceManager.GetString("CPPaginaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change was not successful. Correct the information and try again.
        /// </summary>
        public static string CPSummaryError {
            get {
                return ResourceManager.GetString("CPSummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access.
        /// </summary>
        public static string LogonAcceso {
            get {
                return ResourceManager.GetString("LogonAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been blocked for exceeding access attempts, please notify Zoe IT Department.
        /// </summary>
        public static string LogonBloqueado {
            get {
                return ResourceManager.GetString("LogonBloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string logonBotonEntrar {
            get {
                return ResourceManager.GetString("logonBotonEntrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a company to continue.
        /// </summary>
        public static string LogonCampoEmpresaReq {
            get {
                return ResourceManager.GetString("LogonCampoEmpresaReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Access.
        /// </summary>
        public static string LogonCampoLogin {
            get {
                return ResourceManager.GetString("LogonCampoLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Access Account field is required..
        /// </summary>
        public static string LogonCampoLoginReq {
            get {
                return ResourceManager.GetString("LogonCampoLoginReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LogonCampoPass {
            get {
                return ResourceManager.GetString("LogonCampoPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Password field is required..
        /// </summary>
        public static string LogonCampoPassReq {
            get {
                return ResourceManager.GetString("LogonCampoPassReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password are not valid.
        /// </summary>
        public static string LogonCuentaInvalida {
            get {
                return ResourceManager.GetString("LogonCuentaInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company:.
        /// </summary>
        public static string LogonDialogLblEmp {
            get {
                return ResourceManager.GetString("LogonDialogLblEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the company.
        /// </summary>
        public static string LogonDialogSelectEmp {
            get {
                return ResourceManager.GetString("LogonDialogSelectEmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to get the list of Companies, try again later.
        /// </summary>
        public static string LogonErrorBuscarEmpresa {
            get {
                return ResourceManager.GetString("LogonErrorBuscarEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to search user data.
        /// </summary>
        public static string LogonErrorBuscarUsuario {
            get {
                return ResourceManager.GetString("LogonErrorBuscarUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Information.
        /// </summary>
        public static string LogonFieldSet {
            get {
                return ResourceManager.GetString("LogonFieldSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your username and password.
        /// </summary>
        public static string LogonIntroduzca {
            get {
                return ResourceManager.GetString("LogonIntroduzca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems that the access account belongs to more than one company.
        /// </summary>
        public static string LogonLblMasUnaEmpresa1 {
            get {
                return ResourceManager.GetString("LogonLblMasUnaEmpresa1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the company to be used within the system.
        /// </summary>
        public static string LogonLblMasUnaEmpresa2 {
            get {
                return ResourceManager.GetString("LogonLblMasUnaEmpresa2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a company....
        /// </summary>
        public static string LogonSelectEmpresa {
            get {
                return ResourceManager.GetString("LogonSelectEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username and password are not valid, check your username and password.
        /// </summary>
        public static string LogonSummaryError {
            get {
                return ResourceManager.GetString("LogonSummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access login does not exists.
        /// </summary>
        public static string LogonUsuarioNoExiste {
            get {
                return ResourceManager.GetString("LogonUsuarioNoExiste", resourceCulture);
            }
        }
    }
}
