//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SOEmailResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SOEmailResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SOEmailResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be advised that the Consultant {0} has been asigned.
        /// </summary>
        internal static string AsignadoAviso {
            get {
                return ResourceManager.GetString("AsignadoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe Service Order System, Ticket No. {0} Assigned.
        /// </summary>
        internal static string AsignadoOSSubject {
            get {
                return ResourceManager.GetString("AsignadoOSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can check the status of it, log in with your username and password to Service Orders System http://so.zoeitcustoms.com/.
        /// </summary>
        internal static string CambioStatusSeguimiento {
            get {
                return ResourceManager.GetString("CambioStatusSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe Service Order System, Ticket No. {0} Closed.
        /// </summary>
        internal static string CerradoOSSubject {
            get {
                return ResourceManager.GetString("CerradoOSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Email:{0}, Phone:{1}.
        /// </summary>
        internal static string ContactoDatos {
            get {
                return ResourceManager.GetString("ContactoDatos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe Service Order System, Ticket No. {0}.
        /// </summary>
        internal static string CrearOSSubject {
            get {
                return ResourceManager.GetString("CrearOSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE: Being a public holiday, this service will be attended by the next business day..
        /// </summary>
        internal static string DiaInhabil {
            get {
                return ResourceManager.GetString("DiaInhabil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe IT Customs/Service Order System.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This mail is informative, Please do not respond to this email account !.
        /// </summary>
        internal static string Informativo {
            get {
                return ResourceManager.GetString("Informativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It closed the ticket.
        /// </summary>
        internal static string OSCerrado {
            get {
                return ResourceManager.GetString("OSCerrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Service Order has been created with the Ticket No. {0}.
        /// </summary>
        internal static string OSCreada {
            get {
                return ResourceManager.GetString("OSCreada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that in relation to your request:.
        /// </summary>
        internal static string OSMsg1 {
            get {
                return ResourceManager.GetString("OSMsg1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be advised that the Consultant {0} has been reassigned.
        /// </summary>
        internal static string Reasignacion {
            get {
                return ResourceManager.GetString("Reasignacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe Service Order System, Ticket No. {0} reassigned.
        /// </summary>
        internal static string ReAsignadoOSSubject {
            get {
                return ResourceManager.GetString("ReAsignadoOSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To follow up on the ticket, log in with your username and password to Service Orders System http://so.zoeitcustoms.com/.
        /// </summary>
        internal static string Seguimiento {
            get {
                return ResourceManager.GetString("Seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please be advised that the Consultant {0} has marked as Finished this service order.
        /// </summary>
        internal static string TerminadoAviso {
            get {
                return ResourceManager.GetString("TerminadoAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoe Service Order System, Ticket No. {0} Finished.
        /// </summary>
        internal static string TerminadoOSSubject {
            get {
                return ResourceManager.GetString("TerminadoOSSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket No. {0}.
        /// </summary>
        internal static string TicketNo {
            get {
                return ResourceManager.GetString("TicketNo", resourceCulture);
            }
        }
    }
}
