//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SOResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SOResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SOResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string Actividades {
            get {
                return ResourceManager.GetString("Actividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Anterior {
            get {
                return ResourceManager.GetString("Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultant.
        /// </summary>
        internal static string Asesor {
            get {
                return ResourceManager.GetString("Asesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible Consultant.
        /// </summary>
        internal static string AsesorResponsable {
            get {
                return ResourceManager.GetString("AsesorResponsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string BotonAgregar {
            get {
                return ResourceManager.GetString("BotonAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string BotonCerrarOrdenServicio {
            get {
                return ResourceManager.GetString("BotonCerrarOrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string botonCrearOrdenServicio {
            get {
                return ResourceManager.GetString("botonCrearOrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string CambiarContrasena {
            get {
                return ResourceManager.GetString("CambiarContrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comentario {
            get {
                return ResourceManager.GetString("Comentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Comentarios {
            get {
                return ResourceManager.GetString("Comentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a new comment press the &quot;Add&quot; button.
        /// </summary>
        internal static string ComentlblAgregar {
            get {
                return ResourceManager.GetString("ComentlblAgregar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Activities.
        /// </summary>
        internal static string ConsultarActividades {
            get {
                return ResourceManager.GetString("ConsultarActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contacto {
            get {
                return ResourceManager.GetString("Contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Service Order.
        /// </summary>
        internal static string CrearOrdenServicioTituloPagina {
            get {
                return ResourceManager.GetString("CrearOrdenServicioTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Descripcion {
            get {
                return ResourceManager.GetString("Descripcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new comment to the Service Order.
        /// </summary>
        internal static string DialogAgregarComentario {
            get {
                return ResourceManager.GetString("DialogAgregarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string DialogBotonAceptar {
            get {
                return ResourceManager.GetString("DialogBotonAceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string DialogBotonCancelar {
            get {
                return ResourceManager.GetString("DialogBotonCancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Comment.
        /// </summary>
        internal static string DialogBtnAgregarComentario {
            get {
                return ResourceManager.GetString("DialogBtnAgregarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        internal static string DialogCambiarStatus {
            get {
                return ResourceManager.GetString("DialogCambiarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close this order of service.
        /// </summary>
        internal static string DialogCambiaStatuslbl {
            get {
                return ResourceManager.GetString("DialogCambiaStatuslbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The comment is required.
        /// </summary>
        internal static string DialogCampoComentReq {
            get {
                return ResourceManager.GetString("DialogCampoComentReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Comment is required.
        /// </summary>
        internal static string DialogObsReq {
            get {
                return ResourceManager.GetString("DialogObsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The day.
        /// </summary>
        internal static string ElDia {
            get {
                return ResourceManager.GetString("ElDia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process canceled!, An error occurred while trying to add the comment.
        /// </summary>
        internal static string ErrorAgregarComentario {
            get {
                return ResourceManager.GetString("ErrorAgregarComentario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process canceled!, An error occurred while trying to change the status.
        /// </summary>
        internal static string ErrorCambioStatus {
            get {
                return ResourceManager.GetString("ErrorCambioStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Date.
        /// </summary>
        internal static string FechaInicio {
            get {
                return ResourceManager.GetString("FechaInicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Date.
        /// </summary>
        internal static string FechaRegistro {
            get {
                return ResourceManager.GetString("FechaRegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string FechaTermino {
            get {
                return ResourceManager.GetString("FechaTermino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Activitie Date.
        /// </summary>
        internal static string FechaUltMovimiento {
            get {
                return ResourceManager.GetString("FechaUltMovimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string Historia {
            get {
                return ResourceManager.GetString("Historia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Imprimir {
            get {
                return ResourceManager.GetString("Imprimir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        internal static string IniciarSesion {
            get {
                return ResourceManager.GetString("IniciarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To close the service order, press the button &quot;Close&quot;.
        /// </summary>
        internal static string lblCerrarOrdenServicio {
            get {
                return ResourceManager.GetString("lblCerrarOrdenServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service order has not yet activities .
        /// </summary>
        internal static string lblOSSinActividades {
            get {
                return ResourceManager.GetString("lblOSSinActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service order has no comments yet.
        /// </summary>
        internal static string lblOSSinComentarios {
            get {
                return ResourceManager.GetString("lblOSSinComentarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Service Orders.
        /// </summary>
        internal static string MisOSTituloPagina {
            get {
                return ResourceManager.GetString("MisOSTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string Mostrar {
            get {
                return ResourceManager.GetString("Mostrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service order must be Completed to put it as Closed.
        /// </summary>
        internal static string MsgCerrarOSNoValido {
            get {
                return ResourceManager.GetString("MsgCerrarOSNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service order activities must have completed and / or canceled.
        /// </summary>
        internal static string MsgOSActNoTerminadaCancelada {
            get {
                return ResourceManager.GetString("MsgOSActNoTerminadaCancelada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a ticket to change the status.
        /// </summary>
        internal static string MsgSelecTicketCambiaStatus {
            get {
                return ResourceManager.GetString("MsgSelecTicketCambiaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a ticket.
        /// </summary>
        internal static string MsgSelecTicketSeguimiento {
            get {
                return ResourceManager.GetString("MsgSelecTicketSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service order must be created or tracking to put it as completed.
        /// </summary>
        internal static string MsgTerminarOSNoValido {
            get {
                return ResourceManager.GetString("MsgTerminarOSNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No records found.
        /// </summary>
        internal static string NoRegistros {
            get {
                return ResourceManager.GetString("NoRegistros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Proyecto {
            get {
                return ResourceManager.GetString("Proyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Activities.
        /// </summary>
        internal static string RegistrarActividades {
            get {
                return ResourceManager.GetString("RegistrarActividades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string Registros {
            get {
                return ResourceManager.GetString("Registros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities by Project.
        /// </summary>
        internal static string RepActPorProyecto {
            get {
                return ResourceManager.GetString("RepActPorProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Reports.
        /// </summary>
        internal static string RepAdministracion {
            get {
                return ResourceManager.GetString("RepAdministracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance Policy.
        /// </summary>
        internal static string RepSaldoDePoliza {
            get {
                return ResourceManager.GetString("RepSaldoDePoliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsible.
        /// </summary>
        internal static string Responsable {
            get {
                return ResourceManager.GetString("Responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Off.
        /// </summary>
        internal static string Salir {
            get {
                return ResourceManager.GetString("Salir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing.
        /// </summary>
        internal static string Seguimiento {
            get {
                return ResourceManager.GetString("Seguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string Servicio {
            get {
                return ResourceManager.GetString("Servicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Siguiente {
            get {
                return ResourceManager.GetString("Siguiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assigned Counsltant.
        /// </summary>
        internal static string SinAsesor {
            get {
                return ResourceManager.GetString("SinAsesor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No assigned Project.
        /// </summary>
        internal static string SinProyecto {
            get {
                return ResourceManager.GetString("SinProyecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket Number.
        /// </summary>
        internal static string TicketNumero {
            get {
                return ResourceManager.GetString("TicketNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company/Contact.
        /// </summary>
        internal static string TicketRepClienteEmpresa {
            get {
                return ResourceManager.GetString("TicketRepClienteEmpresa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Closed the selected Service Order.
        /// </summary>
        internal static string tipBotonCerrar {
            get {
                return ResourceManager.GetString("tipBotonCerrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Activities.
        /// </summary>
        internal static string tipBotonSeguimiento {
            get {
                return ResourceManager.GetString("tipBotonSeguimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string Usuario {
            get {
                return ResourceManager.GetString("Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders in which I participate.
        /// </summary>
        internal static string VerParticipoTituloPagina {
            get {
                return ResourceManager.GetString("VerParticipoTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Addressing Service Orders.
        /// </summary>
        internal static string VerSinAtenderTituloPagina {
            get {
                return ResourceManager.GetString("VerSinAtenderTituloPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Volver {
            get {
                return ResourceManager.GetString("Volver", resourceCulture);
            }
        }
    }
}
