//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZOE.OrdenesServicio.Views.Home {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MenuResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZOE.OrdenesServicio.Views.Home.MenuResource", typeof(MenuResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Accion1 {
            get {
                return ResourceManager.GetString("Accion1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Service Order.
        /// </summary>
        public static string Accion10 {
            get {
                return ResourceManager.GetString("Accion10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Service Order.
        /// </summary>
        public static string Accion11 {
            get {
                return ResourceManager.GetString("Accion11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Reports.
        /// </summary>
        public static string Accion12 {
            get {
                return ResourceManager.GetString("Accion12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Areas.
        /// </summary>
        public static string Accion13 {
            get {
                return ResourceManager.GetString("Accion13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Accion14 {
            get {
                return ResourceManager.GetString("Accion14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Accion15 {
            get {
                return ResourceManager.GetString("Accion15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants.
        /// </summary>
        public static string Accion16 {
            get {
                return ResourceManager.GetString("Accion16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Service Order.
        /// </summary>
        public static string Accion17 {
            get {
                return ResourceManager.GetString("Accion17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin Proyecto.
        /// </summary>
        public static string Accion18 {
            get {
                return ResourceManager.GetString("Accion18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Service Orders.
        /// </summary>
        public static string Accion19 {
            get {
                return ResourceManager.GetString("Accion19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Orders.
        /// </summary>
        public static string Accion2 {
            get {
                return ResourceManager.GetString("Accion2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which I participate.
        /// </summary>
        public static string Accion20 {
            get {
                return ResourceManager.GetString("Accion20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Addressing.
        /// </summary>
        public static string Accion21 {
            get {
                return ResourceManager.GetString("Accion21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Completed Service Orders.
        /// </summary>
        public static string Accion22 {
            get {
                return ResourceManager.GetString("Accion22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeja de Asignación.
        /// </summary>
        public static string Accion23 {
            get {
                return ResourceManager.GetString("Accion23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Reports.
        /// </summary>
        public static string Accion24 {
            get {
                return ResourceManager.GetString("Accion24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultas.
        /// </summary>
        public static string Accion3 {
            get {
                return ResourceManager.GetString("Accion3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Accion4 {
            get {
                return ResourceManager.GetString("Accion4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        public static string Accion5 {
            get {
                return ResourceManager.GetString("Accion5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Management.
        /// </summary>
        public static string Accion6 {
            get {
                return ResourceManager.GetString("Accion6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Service Orders.
        /// </summary>
        public static string Accion7 {
            get {
                return ResourceManager.GetString("Accion7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which I participate.
        /// </summary>
        public static string Accion8 {
            get {
                return ResourceManager.GetString("Accion8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without Addressing.
        /// </summary>
        public static string Accion9 {
            get {
                return ResourceManager.GetString("Accion9", resourceCulture);
            }
        }
    }
}
